export const USE_CASE_COMMAND_CLASS = Symbol("USE_CASE_COMMAND_CLASS");
export const USE_CASE_HANDLER_CLASS = Symbol("USE_CASE_HANDLER_CLASS");
export const USE_CASE_HANDLER_METHOD = Symbol("USE_CASE_HANDLER_METHOD");
